[INT-1313][php-onfleet] Delivery Manifest endpoint
onfleet/php-onfleet pull request #15
Opened 2024-05-22 18:13 UTC by lisandrobigi-onfleet

**Describe the solution**
New Onfleet Delivery Manifest API endpoint added as `getDeliveryManifest` method. In order to test the mentioned endpoints, the test file was updated using a dummy object.
https://docs.onfleet.com/reference/delivery-manifest

---

**Added**

- Added getDeliveryManifest endpoint
- Support to include Google Maps Directions API key, in this specific format Google <google_direction_api_key> in your HTTP header as X-API-KEY
- Support for optional query parameters `startDate` and `endDate`.
- The test file was updated
- Readme files were updated to support Workers POST method.

**Changed**

**Deprecated**

**Removed**

**Fixed**

**Security**

2024-05-30 22:13 UTC, danmenza approved these changes
Looks good, approved ✅

2024-05-30 22:35 UTC, ezequielzionDS commented on README.md
> +  "startDate" => "<startDate>", // Optional
I think it would be helpful to include the date format too

2024-05-30 22:36 UTC, ezequielzionDS commented on src/Methods.php
> +					$api->api->headers["X-API-Key"] = 'Google ' . $item['googleApiKey'];
This didn't work for me to get the `turnByTurn` and `totalDistance`

I checked how the headers where being sent and they looked like this:
```
Array
(
    [0] => Content-Type: application/json
    [1] => User-Agent: onfleet/php-onfleet-
    [2] => Authorization: Basic <onfleet-api-key>
    [X-API-Key] => Google <google-api-key>
)
```
It started working when I changed the line to this: 
`$api->api->headers[] = 'X-API-Key: Google ' . $item['googleApiKey'];`
That way, headers will look like this:
```
Array
(
    [0] => Content-Type: application/json
    [1] => User-Agent: onfleet/php-onfleet-
    [2] => Authorization: Basic  <onfleet-api-key>
    [3] => X-API-Key: Google <google-api-key>
)
```

2024-05-30 22:39 UTC, ezequielzionDS requested changes
Aside from only one thing, everything else looks good. I left a suggestion but it's not necessary to make a change for that.

I couldn't make the `startDate` and `endDate` work but I figured that was not an issue since the functionality is set in the "To develop" column in the [jira ticket](https://onfleet.atlassian.net/browse/INT-1654)

2024-05-31 21:23 UTC, ezequielzionDS approved these changes
LGTM ✅

2024-06-03 17:24 UTC, merged